version: '3'
services:
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
